$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: <environment-name>
version: <version>
image: <acr-name>.azurecr.io/<image-name>:<version>
inference_config:
  liveness_route:
    path: /
    port: 5001
  readiness_route:
    path: /
    port: 5001
  scoring_route:
    path: /score
    port: 5001
